"""Replay cache — deterministic, offline model responses keyed by prompt hash.

Three modes:
  live    real model calls, cache untouched
  record  real model calls, responses written to the cache
  replay  no network at all; a cache miss is a hard error, never a silent fallback

The hard error matters. A cache that quietly degrades to a stub would let a broken fixture pass
rehearsal and then fail on camera, which is the exact failure mode §15 warns about.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any

from pathlib import Path

from ..config import DemoMode, Settings
from ..store.base import Repository

# The cache is written to disk and committed. Without this it lived only in the repository's
# process memory, so every backend restart threw it away — which made `replay` mode useless as a
# quota workaround, because the first run after a restart had to hit the models again.
DEFAULT_CACHE_FILE = Path(__file__).resolve().parents[3] / "fixtures" / "replay_cache.json"


class ReplayMiss(RuntimeError):
    """Raised in replay mode when a prompt has no cached response."""


def prompt_hash(agent: str, model: str, prompt: str, context: Any = None) -> str:
    raw = json.dumps(
        {"agent": agent, "model": model, "prompt": prompt, "context": context},
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    )
    return hashlib.sha256(raw.encode()).hexdigest()


class ReplayCache:
    def __init__(
        self, repo: Repository, settings: Settings, cache_file: Path | None = None
    ) -> None:
        self._repo = repo
        self._settings = settings
        self._file = cache_file or DEFAULT_CACHE_FILE
        self._dirty = False

    # --- durability ---------------------------------------------------------

    async def load(self) -> int:
        """Hydrate the cache from disk. Called once at startup."""
        if not self._file.exists():
            return 0
        try:
            payload = json.loads(self._file.read_text())
        except (OSError, json.JSONDecodeError):
            return 0
        entries = payload.get("entries", {})
        for key, value in entries.items():
            await self._repo.put_replay(key, value)
        return len(entries)

    async def flush(self) -> int:
        """Write the cache to disk. Called after a record run.

        Sorted keys and indented output so the committed file diffs cleanly and a reviewer can
        actually read what the models said.
        """
        if not self._dirty:
            return 0
        entries: dict[str, Any] = {}
        for key in list(getattr(self._repo, "_replay", {})):
            value = await self._repo.get_replay(key)
            if value is not None:
                entries[key] = value
        self._file.parent.mkdir(parents=True, exist_ok=True)
        self._file.write_text(
            json.dumps(
                {
                    "note": "Recorded model responses. Generated by `make record`; do not edit "
                            "by hand. Keyed by SHA-256 of (agent, model, prompt, context) — see "
                            "CACHE.md.",
                    "entries": entries,
                },
                indent=2, sort_keys=True,
            ) + "\n"
        )
        self._dirty = False
        return len(entries)

    @property
    def mode(self) -> DemoMode:
        return self._settings.DEMO_MODE

    async def lookup(self, key: str) -> dict[str, Any] | None:
        if self.mode is DemoMode.LIVE:
            return None
        return await self._repo.get_replay(key)

    async def store(self, key: str, payload: dict[str, Any]) -> None:
        if self.mode is DemoMode.RECORD:
            await self._repo.put_replay(key, payload)
            self._dirty = True

    def assert_recordable(self, provider) -> None:
        """Refuse to populate the cache from a non-sanctioned provider.

        The replay cache is what the recorded demo plays back, so a response captured through a
        third-party aggregator would end up in the judged artifact. The rules require Gemini API
        or Vertex AI, so this is a hard stop rather than a warning.
        """
        if self.mode is not DemoMode.RECORD:
            return
        from ..llm.provider import assert_compliant

        assert_compliant(provider)

    async def resolve(self, key: str, call, *, label: str = "") -> dict[str, Any]:
        """Return a cached response, or make the real call if the mode permits one."""
        cached = await self.lookup(key)
        if cached is not None:
            return cached
        if self.mode is DemoMode.REPLAY:
            raise ReplayMiss(
                f"no cached response for {label or key[:12]} (hash {key[:12]}). "
                "Run `make record` against live models to populate the cache; replay mode "
                "never invents a response."
            )
        response = await call()
        await self.store(key, response)
        return response
